### ISSUE TITLE
Can you throttle based on how simulations times a function can be running, and queue up pending functions?

### ISSUE THREAD

**Issue by reggi** [brianloveswords/throttle-function#1]
I was recommended to your module from [this issue](https://github.com/mikeal/request/issues/716) with being limited on how many requests can be sent to an API. I saw in the throttle-function documentation that it was mainly run limit, and temporal based, but not on how many times something is running simultaneously. Ideas?

**Comment by brianloveswords** [comment]
So looking at your original issue, you can solve the problem by doing `throttle(apiCall, { window: 1, limit: 6 })`. This will cause the calls to happen every 167 ms, so you won't go over your 6 calls per second limit. Can you let me know why that won't work for you so I can get a better idea of what you're asking?

**Comment by reggi** [comment]
I guess when I thought about such a limit I was thinking about it in terms of from the requests start and finish, and that until I get a response, only 6 requests could be made. I was think (unnecessarily) that each call couldn't be made consecutively, like your example describes. I think I can get this to work. Thanks for your help.

**Comment by reggi** [comment]
This library doesn't support async? How do I get my data out? Where's my callback / return value? It's returning `{ position: 1, queuedAt: 1386000213061, timeUntilCall: 167 }`

**Comment by brianloveswords** [comment]
Show me how you're trying to call it. The library really _only_ supports async (by that I mean asynchronous function calls, not the library `async`), so I'd like to see how you're using it. Also, check out the example in the readme and see if that clears things up.

**Comment by brianloveswords** [comment]
Here is another example:

``` js

var trottledCall = trottle(function apiCall(callback){ 
  // do some stuff...
  callback(error, result)
}, { window: 1, limit: 6 })

// then you'd call it like you would if it were not throttled:
while (true) {
  throttledCall(function(error, result) {
    if (error) return handleError(error)
    handleResult(result)
  })
}
```

**Comment by reggi** [comment]
I'm trying to wrap a request function. Any idea if i'm doing this right?

``` javascript
Shopify.prototype.prequest = function(options, callback){
    var shopify = this;
    options = helper.janitor.request_options(shopify.settings, options);
    request(options, function (err, response, body){
        console.log(response.headers["x-shopify-shop-api-call-limit"]);
        if(err) return callback(err);
        if(dotty.exists(body, "errors")) return callback(new Error("Shopify : "+options.path+" / "+JSON.stringify(body.errors)), response, body, options);
        if(dotty.exists(body, "error")) return callback(new Error("Shopify : "+options.path+" / "+JSON.stringif(body.error)), response, body, options);
        return callback(null, response, body, options);
    });
};

Shopify.prototype.request = function(options, callback){
    var shopify = this;
    return throttle(shopify.prequest(options, callback), { window: 1, limit: 6 });        
}
```

This could essentially be boiled down to just wrapping a plain request to google.

**Comment by reggi** [comment]
I'm not sure how to test this, how do I know that it's processing only 6 at a time?

``` javascript
var _ = require("underscore");
var async = require("async");
var request = require("request");
var throttle = require('throttle-function');

var google = function(callback){
    request("http://google.com", function(err, response, body){
        if(err) return callback(err);
        console.log(response.statusCode);
        return callback(null, response.statusCode);
    });
}

var google_wrapper = throttle(google, { window: 1, limit: 6 })

async.map(_.range(10), function(number, callback){
    google_wrapper(function(err, result) {
        if(err) return callback(err);
        return callback(null, result);
    });
}, function(err, results){
    if(err) throw err;
    console.log(results);
});
```

**Comment by reggi** [comment]
I set it to throttle by 1 and I can see the output now.

**Comment by reggi** [comment]
I can't seem to get my options passed in, any ideas?

``` javascript

Shopify.prototype.request = function(){
    var shopify = this;
    return throttle(function(options, callback){
        options = helper.janitor.request_options(shopify.settings, options);
        request(options, function (err, response, body){
            console.log(response.headers["x-shopify-shop-api-call-limit"]);
            if(err) return callback(err);
            if(dotty.exists(body, "errors")) return callback(new Error("Shopify : "+options.path+" / "+JSON.stringify(body.errors)), response, body, options);
            if(dotty.exists(body, "error")) return callback(new Error("Shopify : "+options.path+" / "+JSON.stringif(body.error)), response, body, options);
            return callback(null, response, body, options);
        });
    }, { window: 1, limit: 6 });
}();
```

**Comment by reggi** [comment]
Hey, NVM. I got it working by changing that function to "prequest" and adding "this.request = this.prerequest();" to the class.

**Comment by brianloveswords** [comment]
Glad you were able to figure it out!
